const fs = require('fs');
const path = require('path');

const dict = {
  "その他": "Others",
  "AIがカテゴリーを特定できませんでした。出力内容:": "AI failed to categorize. Output:",
  "ログイン": "Login",
  "カテゴリーから探す": "Search by Category",
  "すべて": "All",
  "ユーザー": "Users",
  "すべての結果を表示しました": "All results displayed",
  "検索結果はありません": "No results found",
  "投稿のタイトル、カテゴリー、またはユーザー名を検索...": "Search post titles, categories, or usernames...",
  "検索": "Search",
  "自己紹介はありません": "No bio",
  "読み込み中...": "Loading...",
  "が見つかりませんでした": " not found",
  "戻る": "Back",
  "名無しのユーザー": "Anonymous User",
  "最初のコメントを書きましょう！": "Be the first to comment!",
  "コメントを入力...": "Enter comment...",
  "送信": "Send",
  "ユーザー名（新規作成時のみ）": "Username (only on signup)",
  "ニックネーム": "Nickname",
  "メールアドレス": "Email Address",
  "パスワード": "Password",
  "新規アカウント作成": "Sign Up",
  "既読更新エラー:": "Read update error:",
  "既読にしました！ 部屋ID:": "Marked as read! Room ID:",
  "まだメッセージはありません": "No messages yet",
  "左側のリストから会話を選択してチャットを開始してください。": "Select a conversation from the list to start chatting.",
  "フォロー中のユーザーの投稿がありません": "No posts from users you follow",
  "他のユーザーをフォローしてみましょう": "Let's follow other users",
  "ユーザー名": "Username",
  "🔒 非公開": "🔒 Private",
  "フォローリクエスト": "Follow Requests",
  "詳細": "Details",
  "このアカウントは非公開です": "This account is private",
  "フォローリクエストを送信しました。承認をお待ちください": "Follow request sent. Please wait for approval",
  "フォローすると投稿を見られます": "Follow to see posts",
  "ログインしてフォローすると投稿を見られます": "Login and follow to see posts",
  "プロフィール設定": "Profile Settings",
  "変更する": "Change",
  "表示名": "Display Name",
  "自己紹介 (Bio)": "Bio",
  "パブリックアカウント": "Public Account",
  "プライベートアカウント": "Private Account",
  "投稿が誰にでも表示されます": "Posts are visible to everyone",
  "フォロワーのみ投稿を見られます": "Only followers can see posts",
  "パブリックに設定中": "Setting to Public",
  "プライベートに設定中": "Setting to Private",
  "保存中...": "Saving...",
  "保存する": "Save",
  "ログアウト": "Logout",
  "新しい「やりたいこと」": "New Bucket List Item",
  "例：スカイダイビングをする": "e.g. Go skydiving",
  "カテゴリー": "Category",
  "✨ AIがカテゴリを推測中...": "✨ AI predicting category...",
  "詳細（任意）": "Details (Optional)",
  "キャンセル": "Cancel",
  "追加": "Add",
  "ブロック中のユーザーはいません": "No blocked users",
  "返信": "Reply",
  "▲ 返信を隠す": "▲ Hide replies",
  "達成おめでとう！🎉": "Congratulations! 🎉",
  "写真を選択": "Select Photo",
  "写真をアップロード": "Upload Photo",
  "どんな最高な体験でしたか？": "How was your amazing experience?",
  "記録する": "Record",
  "投稿を編集する": "Edit Post",
  "保存": "Save",
  "まだいません": "No one yet",
  "閉じる": "Close",
  "フォローリクエストはありません": "No follow requests",
  "承認": "Approve",
  "拒否": "Decline",
  "完了にする": "Complete",
  "メニュー": "Menu",
  "編集": "Edit",
  "本当にこの投稿を削除しますか？": "Are you sure you want to delete this post?",
  "削除": "Delete",
  "思い出": "Memories",
  "新しい通知があります": "You have new notifications",
  "通知": "Notifications",
  "すべて既読": "Mark all as read",
  "通知はありません": "No notifications",
  "詳細設定": "Advanced Settings",
  "ブロックすると、このユーザーの投稿やメッセージが表示されなくなります。": "Blocking this user will hide their posts and messages.",
  "処理中...": "Processing...",
  "ユーザー名を入力してください": "Please enter a username",
  "プロフィール保存エラー:": "Profile save error:",
  "確認メールを送信しました！メール内のリンクをクリックして登録を完了させてください。": "Confirmation email sent! Click the link in the email to complete registration.",
  "ログイン成功！": "Login successful!",
  "コメント取得エラー:": "Comment fetch error:",
  "ログインが必要です": "Login required",
  "更新に失敗しました": "Update failed",
  "削除に失敗しました": "Delete failed",
  "詳細エラー:": "Detail error:",
  "メッセージルームの作成に失敗しました": "Failed to create message room",
  "アイコンを更新しました！": "Icon updated!",
  "保存に失敗しました": "Save failed",
  "保存しました！": "Saved!",
  "ログアウトに失敗しました": "Logout failed",
  "旅行（日本）": "Travel (Japan)",
  "旅行（海外）": "Travel (International)",
  "旅行（レジャー・アクティビティー）": "Travel (Leisure/Activity)",
  "旅行（その他）": "Travel (Others)",
  "グルメ（レストラン・カフェ）": "Food (Restaurant/Cafe)",
  "グルメ（料理）": "Food (Cooking)",
  "グルメ（その他）": "Food (Others)",
  "学習・スキル（資格）": "Learning/Skill (Certification)",
  "学習・スキル（語学）": "Learning/Skill (Language)",
  "学習・スキル（受験）": "Learning/Skill (Exam)",
  "学習・スキル（ITスキル）": "Learning/Skill (IT)",
  "学習・スキル（ビジネススキル）": "Learning/Skill (Business)",
  "学習・スキル（その他）": "Learning/Skill (Others)",
  "健康（ダイエット）": "Health (Diet)",
  "健康（筋トレ）": "Health (Workout)",
  "健康（生活習慣改善）": "Health (Lifestyle)",
  "健康（メンタルヘルス）": "Health (Mental)",
  "健康（スポーツ）": "Health (Sports)",
  "健康（その他）": "Health (Others)",
  "キャリア（就職）": "Career (Employment)",
  "キャリア（転職）": "Career (Job Change)",
  "キャリア（昇進）": "Career (Promotion)",
  "キャリア（副業）": "Career (Side Job)",
  "キャリア（フリーランス）": "Career (Freelance)",
  "キャリア（起業）": "Career (Entrepreneurship)",
  "キャリア（その他）": "Career (Others)",
  "お金（貯金）": "Money (Savings)",
  "お金（投資）": "Money (Investment)",
  "お金（資産形成）": "Money (Asset Building)",
  "お金（その他）": "Money (Others)",
  "趣味（コレクション）": "Hobby (Collection)",
  "趣味（イラスト）": "Hobby (Illustration)",
  "趣味（音楽）": "Hobby (Music)",
  "趣味（DIY）": "Hobby (DIY)",
  "趣味（写真）": "Hobby (Photography)",
  "趣味（その他）": "Hobby (Others)",
  "エンタメ（映画）": "Entertainment (Movies)",
  "エンタメ（ドラマ）": "Entertainment (Drama)",
  "エンタメ（アニメ）": "Entertainment (Anime)",
  "エンタメ（漫画）": "Entertainment (Manga)",
  "エンタメ（ライブ・フェス）": "Entertainment (Live/Festivals)",
  "エンタメ（その他）": "Entertainment (Others)",
  "ファッション・美容（コーディネート）": "Fashion/Beauty (Coordination)",
  "ファッション・美容（ブランド）": "Fashion/Beauty (Brands)",
  "ファッション・美容（ショッピング）": "Fashion/Beauty (Shopping)",
  "ファッション・美容（スキンケア）": "Fashion/Beauty (Skincare)",
  "ファッション・美容（メイク）": "Fashion/Beauty (Makeup)",
  "ファッション・美容（ヘアスタイル）": "Fashion/Beauty (Hairstyle)",
  "ファッション・美容（美容医療）": "Fashion/Beauty (Cosmetic Surgery)",
  "ファッション・美容（その他）": "Fashion/Beauty (Others)",
  "ライフスタイル・住まい": "Lifestyle/Home"
};

const files = fs.readFileSync('extract_ja.js').toString() ? [
"actions/categorize.ts",
"app/components/Nav.tsx",
"app/explore/components/CategoryFilter.tsx",
"app/explore/components/ExploreContent.tsx",
"app/explore/components/ExploreTabBar.tsx",
"app/explore/components/InfiniteScrollTrigger.tsx",
"app/explore/components/ItemList.tsx",
"app/explore/components/SearchBar.tsx",
"app/explore/components/UserList.tsx",
"app/explore/page.tsx",
"app/item/[id]/page.tsx",
"app/login/page.tsx",
"app/messages/[id]/page.tsx",
"app/messages/components/RoomListItem.tsx",
"app/messages/layout.tsx",
"app/messages/page.tsx",
"app/page.tsx",
"app/profile/[id]/page.tsx",
"app/profile/settings/page.tsx",
"components/AddItemModal.tsx",
"components/BlockListModal.tsx",
"components/CommentItem.tsx",
"components/CompleteItemModal.tsx",
"components/EditItemModal.tsx",
"components/FollowListModal.tsx",
"components/FollowRequestsModal.tsx",
"components/ItemCard.tsx",
"components/NotificationDropdown.tsx",
"components/UserOptionsModal.tsx",
"hooks/useAuthForm.ts",
"hooks/useBlock.ts",
"hooks/useExplore.ts",
"hooks/useExploreNavigation.ts",
"hooks/useFollowRequests.ts",
"hooks/useItemDetail.ts",
"hooks/useMessageRooms.ts",
"hooks/useNav.ts",
"hooks/useProfile.ts",
"hooks/useProfileSettings.ts",
"hooks/useTimeline.ts",
"lib/categories.ts",
"lib/constants.ts",
"lib/notifications.ts"
] : [];

files.forEach(file => {
    try {
        let content = fs.readFileSync(file, 'utf8');
        for (const [ja, en] of Object.entries(dict)) {
            // regex to replace exactly the string safely
            content = content.split(ja).join(en);
        }
        fs.writeFileSync(file, content);
    } catch (e) {
        console.error('Error with file', file, e);
    }
});

console.log('Replacement done.');
