export const CATEGORIES = [
  "Travel (Japan)",
  "Travel (International)",
  "Travel (Leisure/Activity)",
  "Travel (Others)",
  "Food (Restaurant/Cafe)",
  "Food (Cooking)",
  "Food (Others)",
  "Learning/Skill (Certification)",
  "Learning/Skill (Language)",
  "Learning/Skill (Exam)",
  "Learning/Skill (IT)",
  "Learning/Skill (Business)",
  "Learning/Skill (Others)",
  "Health (Diet)",
  "Health　(Workout)",
  "Health (Lifestyle)",
  "Health (Mental)",
  "Health (Sports)",
  "Health (Others)",
  "Career (Employment)",
  "Career (Job Change)",
  "Career (Promotion)",
  "Career (Side Job)",
  "Career (Freelance)",
  "Career (Entrepreneurship)",
  "Career (Others)",
  "Money (Savings)",
  "Money (Investment)",
  "Money (Asset Building)",
  "Money (Others)",
  "Hobby (Collection)",
  "Hobby (Illustration)",
  "Hobby (Music)",
  "Hobby (DIY)",
  "Hobby (Photography)",
  "Hobby (Others)",
  "Entertainment (Movies)",
  "Entertainment (Drama)",
  "Entertainment (Anime)",
  "Entertainment (Manga)",
  "Entertainment (Live/Festivals)",
  "Entertainment (Others)",
  "Fashion/Beauty (Coordination)",
  "Fashion/Beauty (Brands)",
  "Fashion/Beauty (Shopping)",
  "Fashion/Beauty (Skincare)",
  "Fashion/Beauty (Makeup)",
  "Fashion/Beauty (Hairstyle)",
  "Fashion/Beauty (Cosmetic Surgery)",
  "Fashion/Beauty (Others)",
  "Lifestyle/Home",
  "Others"

];
